[pytest]
filterwarnings =
    ignore:'setName' deprecated - use 'set_name':DeprecationWarning:httplib2\.auth
    ignore:'leaveWhitespace' deprecated - use 'leave_whitespace':DeprecationWarning:httplib2\.auth
    ignore:'setParseAction' deprecated - use 'set_parse_action':DeprecationWarning:httplib2\.auth
    ignore:'addParseAction' deprecated - use 'add_parse_action':DeprecationWarning:httplib2\.auth
    ignore:'delimitedList' deprecated - use 'DelimitedList':DeprecationWarning:httplib2\.auth
    ignore:Inheritance class ClientSession from ClientSession is discouraged:DeprecationWarning:openbb_core\.provider\.utils\.client
    ignore:Using `@model_validator` with mode='after' on a classmethod is deprecated\..*:DeprecationWarning:openbb_.*
    ignore:Accessing the 'model_fields' attribute on the instance is deprecated\..*:DeprecationWarning:openbb_core\.app\.model\.credentials
